# Generated by Django 4.1.3 on 2022-11-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
